### ISSUE TITLE
支持嵌入vue以及react等前端框架吗？

### ISSUE THREAD

**Issue by pl1998** [KingBes/framework#1]
### 支持嵌入vue以及react等前端框架吗？
可以参考 https://github.com/wailsapp/wails

**Comment by KingBes** [comment]
目前只考虑传统的和开箱即用的js

**Comment by pl1998** [comment]
其实也不复杂，vue或者react打包后也是一个单页面应用，入口也是一个index.html

**Comment by KingBes** [comment]
是的，但是单页面应用也意味着，大多功能都要写在一个控制器上面
